---
- name: 'Install packages'
  hosts: all
  become: true
  tasks:
    - name: Update archlinux-keyring
      shell: "rm -f /var/lib/pacman/db.lck"
    - name: Sync and refresh package database
      shell: "pacman -Sy"
    - name: Install iptables-nft
      shell: "yes | pacman -S --needed iptables-nft"
    - name: Install packages from package list
      become: false
      shell: |
        yes | sudo pacman -S --needed - < /home/arch/pkglist.txt --noconfirm
        rm /home/arch/pkglist.txt
    - name: Install yay
      become: false
      shell: |
        git clone https://aur.archlinux.org/yay.git
        cd yay
        yes | makepkg -si
        rm -rf yay

- name: 'Start and enable services'
  hosts: all
  become: true
  tasks:
    - name: Enable Qemu guest agent
      shell: "systemctl enable --now qemu-guest-agent"
    - name: Enable Docker
      shell: "systemctl enable --now docker"

- name: 'Install zsh along with theme'
  hosts: all
  become: false
  tasks:
    - name: Install theme dependencies
      shell: |
        sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    - name: Copy theme settings
      shell: |
        git clone https://github.com/Naman1997/Terminal-themes.git
        cp Terminal-themes/zsh/.z* /home/arch/
        rm -rf Terminal-themes/
    # - name: Switch default terminal to be zsh
    #   expect:
    #     command: "chsh -s /usr/bin/zsh"
    #     responses:
    #       (?i)password: "arch"