name: Validatate configs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ansible
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
      
      # Check syntax for all ansible playbooks
      - name: Validate all playbooks
        run: ansible-playbook playbook.yml --syntax-check
  packer:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: archlinux.pkr.hcl
